% New function for fitting ellipse based on stuff I understand
function center = ellipsoid_fit2( X )
x = X( :, 1 );
y = X( :, 2 );
z = X( :, 3 );

% Form A matrix
D = [ x .* x , ...
    2*x.*y, ...
    2*x.*z, ...
    2 * x, ...
    y.*y, ...
    2 * y .* z, ...
    2 * y, ...
    z.*z, ...
    2*z];

% solve the normal system of equations
d2 = ones(size(D,1),1); % the RHS of the llsq problem (y's)
w = ( D' * D ) \ ( D' * d2 );

V_inv = [w(1), w(2), w(3);...
         w(2), w(5), w(6);...
         w(3), w(6), w(8)];

center = -V_inv\ [ w(4); w(7); w(9)];


end