# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ayotundedemuren/.local/lib/python3.6/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/ayotundedemuren/.local/lib/python3.6/site-packages/cmake/data/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ayotundedemuren/Documents/GNC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ayotundedemuren/Documents/GNC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/ayotundedemuren/.local/lib/python3.6/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/ayotundedemuren/.local/lib/python3.6/site-packages/cmake/data/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ayotundedemuren/Documents/GNC/CMakeFiles /home/ayotundedemuren/Documents/GNC/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ayotundedemuren/Documents/GNC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named triad_cpp

# Build rule for target.
triad_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triad_cpp
.PHONY : triad_cpp

# fast build rule for target.
triad_cpp/fast:
	$(MAKE) -f CMakeFiles/triad_cpp.dir/build.make CMakeFiles/triad_cpp.dir/build
.PHONY : triad_cpp/fast

#=============================================================================
# Target rules for targets named time_functions_cpp

# Build rule for target.
time_functions_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 time_functions_cpp
.PHONY : time_functions_cpp

# fast build rule for target.
time_functions_cpp/fast:
	$(MAKE) -f CMakeFiles/time_functions_cpp.dir/build.make CMakeFiles/time_functions_cpp.dir/build
.PHONY : time_functions_cpp/fast

#=============================================================================
# Target rules for targets named sun_utils_cpp

# Build rule for target.
sun_utils_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sun_utils_cpp
.PHONY : sun_utils_cpp

# fast build rule for target.
sun_utils_cpp/fast:
	$(MAKE) -f CMakeFiles/sun_utils_cpp.dir/build.make CMakeFiles/sun_utils_cpp.dir/build
.PHONY : sun_utils_cpp/fast

# target to build an object file
TRIAD/cpp/deterministic_ad.o:
	$(MAKE) -f CMakeFiles/triad_cpp.dir/build.make CMakeFiles/triad_cpp.dir/TRIAD/cpp/deterministic_ad.o
.PHONY : TRIAD/cpp/deterministic_ad.o

# target to preprocess a source file
TRIAD/cpp/deterministic_ad.i:
	$(MAKE) -f CMakeFiles/triad_cpp.dir/build.make CMakeFiles/triad_cpp.dir/TRIAD/cpp/deterministic_ad.i
.PHONY : TRIAD/cpp/deterministic_ad.i

# target to generate assembly for a file
TRIAD/cpp/deterministic_ad.s:
	$(MAKE) -f CMakeFiles/triad_cpp.dir/build.make CMakeFiles/triad_cpp.dir/TRIAD/cpp/deterministic_ad.s
.PHONY : TRIAD/cpp/deterministic_ad.s

# target to build an object file
util_funcs/cpp/sun_utils.o:
	$(MAKE) -f CMakeFiles/sun_utils_cpp.dir/build.make CMakeFiles/sun_utils_cpp.dir/util_funcs/cpp/sun_utils.o
.PHONY : util_funcs/cpp/sun_utils.o

# target to preprocess a source file
util_funcs/cpp/sun_utils.i:
	$(MAKE) -f CMakeFiles/sun_utils_cpp.dir/build.make CMakeFiles/sun_utils_cpp.dir/util_funcs/cpp/sun_utils.i
.PHONY : util_funcs/cpp/sun_utils.i

# target to generate assembly for a file
util_funcs/cpp/sun_utils.s:
	$(MAKE) -f CMakeFiles/sun_utils_cpp.dir/build.make CMakeFiles/sun_utils_cpp.dir/util_funcs/cpp/sun_utils.s
.PHONY : util_funcs/cpp/sun_utils.s

# target to build an object file
util_funcs/cpp/time_functions.o:
	$(MAKE) -f CMakeFiles/time_functions_cpp.dir/build.make CMakeFiles/time_functions_cpp.dir/util_funcs/cpp/time_functions.o
.PHONY : util_funcs/cpp/time_functions.o

# target to preprocess a source file
util_funcs/cpp/time_functions.i:
	$(MAKE) -f CMakeFiles/time_functions_cpp.dir/build.make CMakeFiles/time_functions_cpp.dir/util_funcs/cpp/time_functions.i
.PHONY : util_funcs/cpp/time_functions.i

# target to generate assembly for a file
util_funcs/cpp/time_functions.s:
	$(MAKE) -f CMakeFiles/time_functions_cpp.dir/build.make CMakeFiles/time_functions_cpp.dir/util_funcs/cpp/time_functions.s
.PHONY : util_funcs/cpp/time_functions.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... triad_cpp"
	@echo "... rebuild_cache"
	@echo "... time_functions_cpp"
	@echo "... sun_utils_cpp"
	@echo "... TRIAD/cpp/deterministic_ad.o"
	@echo "... TRIAD/cpp/deterministic_ad.i"
	@echo "... TRIAD/cpp/deterministic_ad.s"
	@echo "... util_funcs/cpp/sun_utils.o"
	@echo "... util_funcs/cpp/sun_utils.i"
	@echo "... util_funcs/cpp/sun_utils.s"
	@echo "... util_funcs/cpp/time_functions.o"
	@echo "... util_funcs/cpp/time_functions.i"
	@echo "... util_funcs/cpp/time_functions.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

